print("\nHi, wait a second, everything will be set up in just a second...\n")
shell.run("wget run https://github.com/9551-Dev/Gui-h/raw/main/installer.lua")
shell.run("mkdir Better_Dig")
shell.run("cd Better_Dig")
shell.run("pastebin get krYgvnpL func.lua")
shell.run("pastebin get Fyy4cQmU better_dig")
shell.run("pastebin get EerUDV2A location_set")
shell.run("pastebin get uPSuc3vU connect_display.lua")
shell.run("cd ..")
shell.run("pastebin get DzN8922h startup.lua")
print("Please Name your Turtle: ")
local input = io.read()
shell.run(os.setComputerLabel(input))
print("\nTurtle's name now is: " .. input)
print("\nEverything ready! ")